apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditsnttpf
  labels:
    app: creditsnttpf
spec:
  replicas: 1
  selector:
    matchLabels:
      service: creditsnttpf
  template:
    metadata:
      labels:
        app: creditsnttpf
        service: creditsnttpf
    spec:
      containers:
        - name: creditsnttpf
          image: creditsnttpf.azurecr.io/creditsnttpf:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8082
            - name: WebApiBaseAddress
              value: http://webapi