apiVersion: v1
kind: Service
metadata:
  name: creditsnttpf
  labels:
    app: creditsnttpf
    service: creditsnttpf
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    service: creditsnttpf